lc0/src/neural/cuda/winograd_helper.inc
lc0/src/neural/sycl/layers.cc.dp.cpp
lc0/src/neural/sycl/winograd_helper.h

Pull request has 2 changes 
1.) Added loop unrolling to Winograd kernels
2.) Updated interop calls for SYCL version to cuBlas and hipBlas libraries.

[Lc0][SYCL][CUDA] Update to interop calls and loop unrolling

---

lc0/README.md
lc0/meson_options.txt

[Lc0][Level Zero] Changed compilation of kernels for Level Zero backend to be JIT for default. User can still specify AOT if they wish.

[Lc0][Level Zero] Changed compilation of kernels for Level Zero backend to be JIT 

---

cudaSift/CUDA/CMakeLists.txt
cudaSift/CUDA/mainSift.cpp
cudaSift/HIP/CMakeLists.txt
cudaSift/HIP/mainSift.cpp
cudaSift/README.md
cudaSift/SYCL/CMakeLists.txt
cudaSift/SYCL/cudaImage.dp.cpp
cudaSift/SYCL/cudaSiftD.dp.cpp
cudaSift/SYCL/cudaSiftH.dp.cpp
cudaSift/SYCL/infra/atomic.hpp
cudaSift/SYCL/infra/device.hpp
cudaSift/SYCL/infra/memory.hpp
cudaSift/SYCL/mainSift.cpp
cudaSift/SYCL/matching.dp.cpp
cudaSift/common/Utility.cpp
cudaSift/common/Utility.h

- Updated cmake files, allows passing in additional flags which overrides default flags.
- Updated main program in all three versions to return -1 when data verification failed.
- Fixed sycl math call to use sycl::pow instead of sycl::pow<float> which causes compilation issue.
- Updated SYCL version to not use sub group size while on nvidia and amd backends.
- Used local_space inside barriers and loop unrolling which improved SYCL performance by 7%

[Cudasift][SYCL][HIP][CUDA]Minor fixes and perf improvements

---

svm/SYCL/CMakeLists.txt
svm/SYCL/cmake/FindSYCL.cmake

Using [oneMKL interface](https://github.com/oneapi-src/oneMKL) instead of the [oneMKL library](https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2023-0/intel-oneapi-math-kernel-library-onemkl.html) when building this benchmarks adds flexibility, as oneMKL can use different backends, including the oneMKL library itself.

[svm][SYCL] Use oneMKL interface instead of oneMKL library

---

easywave/SYCL/src/ewGpuNode.cpp

Instead of just checking `icpx`, also check for `clang++` in `#if` directive.

[easywave][SYCL] Avoid invalid work-group size with DPC++

---

reverse_time_migration/libs/SeismicOperations/src/components/concrete/oneapi/boundary-managers/extensions/MinExtension.cpp

- In preparation for `sycl.hpp` for removing `cmath.h`

[reverse_time_migration] Insert <cmath> header

---

cudaSift/CUDA/cudaSiftH.cu
cudaSift/HIP/cudaSiftH.cpp
cudaSift/SYCL/cudaSiftH.dp.cpp

- Used LowPassBlock function instead of LowPassBlockOld to address the issue of verification failure when loop unrolling is removed in SYCL version.
- Used the same function in CUDA and HIP versions too.

[Cudasift] Used LowPassBlock instead of LowPassBlockOld

---

cudaSift/SYCL/CMakeLists.txt

Removed USE_DEFAULT_FLAGS flag from Cmake script which is no more required.

[Cudasift][SYCL] removed USE_DEFAULT_FLAGS

---

cudaSift/HIP/CMakeLists.txt
cudaSift/SYCL/cudaSiftD.dp.cpp

1. Bug fix for seq_mem in SYCL version not building on AMD backend. This required updating a SYCL atomic function.
2. Updated HIP Cmake, removed unwanted settings.

Cudasift - Fix SYCL failure on AMD Backend

---

ethminer/libethash-sycl/dagger_shuffled.dp.hpp

Addressing the issue of [Lower unreachable to exit to allow ptxas to accurately reconstruct the CFG](https://reviews.llvm.org/D152789) could potentially result in performance regression through adding a basic block with an `exit` to the end of the CFG. An example demonstrating noticeable regression resulting from this change can be found in [ethminer](https://github.com/oneapi-src/Velocity-Bench/tree/main/ethminer), where the code is built using DPC++ for the A100 CUDA backend, using below commands.
```
CC="clang" CXX="clang++ -fsycl -fsycl-unnamed-lambda" cmake .. -DUSE_SM=80 -DUSE_NVIDIA_BACKEND=ON -DETHASHSYCL=ON -G Ninja
ninja
```
The performance regression in the sample comes from a switch statement with an unreachable default which is lowered to `exit` and moved to the end of the …

[ethminer] Remove unreachable default case in switch statements to prevent potential performance regression.

---

THIRD-PARTY-PROGRAMS
voxelizer/HIP/CMakeLists.txt
voxelizer/LICENSE
voxelizer/README.md
voxelizer/SYCL/CMakeLists.txt

- Updated cmake files for SYCL and HIP versions to fix build issues.
- Updates THIRD-PARTY-PROGRAMS file to add voxelizer license info
- Added voxelizer license file inside its voxelizer folder

[Voxelizer] Updated CMake files in SYCL and HIP

---

QuickSilver/SYCL/src/main.cc.dp.cpp

Removed the usage of ishost api which is deprecated from the SYCLOS compiler.

[Quicksilver][SYCL] Remove deprecated api

---

cudaSift/SYCL/infra/device.hpp

Removed the usage of ishost api which is deprecated from the SYCLOS compiler.

[Cudasift][SYCL] Remove deprecated api

---

dl-cifar/SYCL/basic-dl/lnorm_layer.h
dl-cifar/SYCL/basic-dl/softmax_layer.h
dl-cifar/SYCL/blas_routines.h
dl-cifar/SYCL/handle.h
dl-cifar/SYCL/upsample.h
dl-mnist/SYCL/tensor_mgr.onednn.h
easywave/SYCL/src/EasyWave.cpp
easywave/SYCL/src/ewCudaKernels.cpp
easywave/SYCL/src/ewCudaKernels.hpp
easywave/SYCL/src/ewGpuNode.cpp
easywave/SYCL/src/ewGpuNode.hpp
ethminer/libethash-sycl/SYCLMiner.cpp
ethminer/libethash-sycl/SYCLMiner.h
ethminer/libethash-sycl/dagger_shuffled.dp.hpp
ethminer/libethash-sycl/dpcpp_helper.h
ethminer/libethash-sycl/ethash_sycl_miner_kernel.cpp
ethminer/libethash-sycl/ethash_sycl_miner_kernel.h
ethminer/libethash-sycl/ethash_sycl_miner_kernel_globals.h
ethminer/libethash-sycl/fnv.dp.hpp
ethminer/libethash-sycl/keccak.dp.hpp
infrastructure/SYCL.h
lc0/src/neural/sycl/cuBlasContext.h
reverse_time_migration/libs/SeismicOperations/include/operations/backend/OneAPIBackend.hpp
reverse_time_migration/src/generators/concrete/computation-parameters/oneapi/computation_parameters_generator.cpp

LLVM requires to include <sycl/sycl.hpp>

Fix of <sycl.hpp> includes

---

hashtable/CUDA/src/main.cpp
hashtable/HIP/src/main.cpp
hashtable/README.md
hashtable/SYCL/src/main.cpp

This PR adds a cmdline option `--seed` to hastable benchmark to be able to specify the seed for the random number generator that is used to specify how much we would run the program. That is helpful to normalize the results across runs.

Add seed cmdline option to hastable benchmark

---

easywave/SYCL/src/EasyWave.cpp

Allow comparing SYCL timing to other programming models by restoring the timing print-outs.

[easywave][SYCL] Uncomment timing print-out

---

voxelizer/SYCL/src/infra/device.hpp

Fix the old copy of DPCT device.hpp header by replacing the `set_max_clock_frequency` configuration with a version from a recent DPCT release. The old code called the function `is_host()` which was not defined anywhere in this repository and failed to compile. There is no host device in SYCL2020 anyway, so the removed branch would never be taken.

[voxelizer][SYCL] Remove host-device workaround

---

tsne/SYCL/src/kernels/perplexity_search.dp.cpp

Fix the initialisation of the reduction object by passing a property list rather than a single property. The latter fails in newer DPC++ versions with:
```
error: no member named 'has_property' in 'sycl::property::reduction::initialize_to_identity'
```

[tsne][SYCL] Use property_list instead of property value

---

SeisAcoMod2D/CUDA/CMakeLists.txt

The flag `-L` should be only applied to directories containing libraries, not to absolute paths to library files. Fix the flags by removing `-L` which was resulting in flags like these being added: `-L/path/to/libmpicxx.so -L/path/to/libcudart_static.a` and the linker failing.

[SeisAcoMod2D][CUDA] Fix incorrect linking flags

---

hplinpack/dpcpp/hpl-2.3/src/dpcpp/dpcpp_dgemm.h

The use of `cl::sycl::` in place of `sycl::` is deprecated in SYCL2020 and causes the compilation to fail in recent DPC++ versions with:
```
error: use of undeclared identifier 'cl'
```
Fix this by using just the `sycl::` namespace.

[hplinpack][SYCL] Fix the use of deprecated namespace

---

dl-mnist/CUDA/main.cudnn.cpp
dl-mnist/HIP/main.miopen.cpp
dl-mnist/SYCL/main.onednn.cpp

Add an extra timer to measure just the computation time without initialisation. Print both at the end.

[dl-mnist] Print both total and compute-only times

---

dl-cifar/CUDA/main.cuda.cpp
dl-cifar/HIP/main.hip.cpp
dl-cifar/SYCL/main.sycl.cpp

Add an extra timer to measure just the computation time without initialisation. Print both at the end.

[dl-cifar] Print both total and compute-only times

---

easywave/CUDA/src/EasyWave.cpp
easywave/HIP/src/EasyWaveGen.cpp
easywave/SYCL/src/EasyWave.cpp

Add an extra timer to measure just the computation time without initialisation. Print both at the end.
Also fix the I/O time printout which should be the sum of read and write, not the difference.

[easywave] Print both total and compute-only times

---

hashtable/CUDA/src/main.cpp
hashtable/HIP/src/main.cpp
hashtable/SYCL/src/main.cpp

Add an extra timer to measure just the computation time without initialisation. Print both at the end. Use the compute-only time to calculate "keys/second".

[hashtable] Print both total and compute-only times

---

lc0/src/neural/sycl/layers.cc.dp.cpp

Fix incorrect dereference and assignment causing a segfault. Also use the templated `malloc_device` to avoid C-style casting and make the code clearer.
The code creates an uninitialised pointer and intends to assign a value to this pointer (location of newly allocated memory). However, it was previously trying to assign the value to the pointed-to location not the pointer itself, hence it was dereferencing the uninitialised pointer.

[lc0][SYCL] Fix segfault
